### ISSUE TITLE
Illegal redistribution

### ISSUE THREAD

**Issue by peterix** [flathub/com.mojang.Minecraft#27]
Basically, this shouldn't exist.

**Comment by Kekun** [comment]
Why is it illegal, and in which countries?

We don't distribute anything, the game is fetched from Mojang on the user's computer, I don't think this is illegal in any country.

**Comment by barthalion** [comment]
@peterix 

It is not technically redistribution of your application, it is a simply a wrapper which allows easier installation of unmodified Minectaft launcher, downloaded directly from Mojang server from the users computer. The integrity is ensured by both file size check but also checksum as seen in the manifest file in the repository.

I understand it may cause confusion and we can add disclaimer saying that the wrapper is not verified by, affiliated with, or supported by your company.

That being said, the primary goal of Flathub is to enable application developers to maintain their application themselves and we would be more than happy to grant you access to the Flathub repository. In order to do so, we will need to know GitHub usernames that should have write access and we will invite them.

**Comment by AsciiWolf** [comment]
@barthalion Well said. :-) Also, there is a clear notice in the AppData file that this package is unofficial.

**Comment by Kekun** [comment]
@peterix: I see you are working on the launcher at Mojang, stating it would have helped in understanding your motivation. :)

Regardless, @barthalion said all that matters: please help maintain this to make Minecraft more accessible to Linux players! :D

**Comment by peterix** [comment]
Hmmm. If the result is produced on the user's system, then that changes the situation.

Feel free to close this.

**Comment by AsciiWolf** [comment]
@peterix Thanks. Feel free to let us know if you want push access to this repository to help us maintaining this Flatpak. ;-)

**Comment by peterix** [comment]
It would be worth looking into if flatpak could map high level dependencies (specific ABI versions of specific libraries) to system packages, and install them for the user no matter how they are named.

Otherwise, this will simply be an infinite source of strange issues.

**Comment by alexlarsson** [comment]
@peterix The whole point of flatpak is to not rely on system packages for ABI. All the required dependencies are made available with a fixed ABI that is independent of what is available in the distro.
