### ISSUE TITLE
Update name to "Minecraft: Java Edition"

### ISSUE THREAD

**Issue by cassidyjames** [flathub/com.mojang.Minecraft#46]
As of [June 2017](https://www.minecraft.net/en-us/article/all-news-e3), Microsoft and Mojang officially renamed Minecraft to "Minecraft: Java Edition" because they renamed the other versions (previously codenamed "Bedrock edition") to just "Minecraft". 

The new Minecraft is:
1. Paid to download, 
2. Uses Xbox Live for accounts, and 
3. Has cross-play between Android, iOS, Switch, Xbox, and Windows 10. 

Java Edition is:
1. Free to download, 
2. Requires a paid Mojang account, and 
3. Only supports playing with other Java users. 

Due to these substantial differences, **Java Edition on Flathub really needs to clearly include "Java Edition" in its title**. This is consistent with how Mojang advertises it on the [download page](https://www.minecraft.net/en-us/download/) and [informational page](https://www.minecraft.net/en-us/store/minecraft-java-edition/).

**Comment by AsciiWolf** [comment]
Thanks for your PR, I appreciate it, however I don't think that this is a good idea. The official deb file is also called "Minecraft" and has the installed desktop entry called "Minecraft Launcher". Information that this is actually a Java version is displayed only in the game launcher window. See this screenshot:
![launcher_mc](https://user-images.githubusercontent.com/2339930/77947460-3bc2cc80-72c4-11ea-806b-c11156b3ba52.png)

It probably could be a good idea to add the information that this is a Java Edition to AppData `<description>` tag, but it would be necessary to modify this for all languages, not only English.

**Comment by cassidyjames** [comment]
@AsciiWolf the name of the deb isn't really relevant, as it could be called `installer.deb`. I can understand reverting the .desktop change, but the title really **must** be `Minecraft: Java Edition` in the store because it is an entirely different game with a different payment structure and features from what is actually called `Minecraft`. Otherwise you're advertising a completely different game under the wrong name.

**Comment by AsciiWolf** [comment]
This is an actual Minecraft game and it is the main edition of the game since most online servers and most PC players (still) use this instead of the (more limited) Bedrock Edition (also called as "Minecraft for Windows 10" on PC) that is not available for Linux, macOS or Windows 7. Also, I was not talking just about the deb file name, but also about its metadata where it is called "Official Minecraft Launcher".

By the way, this Flatpak also serves as a replacement for the original Endless OS one that was also called "Minecraft". Same thing on Linux Mint, where the Java Edition is also packaged as "Minecraft" or Ubuntu Snap Store with "Minecraft Installer", and many other examples. Basically Minecraft on PC = Minecraft: Java Edition and Bedrock Edition = mobile/console edition that can also be played on Windows 10.

As I said, changing "Minecraft", for example, to "Minecraft (Java Edition)" in AppData `<description>` could be a good idea (and I would happily merge such PR) since Flatpak/Flathub will also be used on Librem 5 and other mobile GNU/Linux devices and can be confusing there, but I really don't think it makes any sense to rename this Flatpak - it would just make things more confusing for users, at least in my opinion.

@nedrichards @bilelmoussaoui What is your opinion guys?

**Comment by cassidyjames** [comment]
Yeah the problem is that Mojang very explicitly and officially renamed this to Java Edition and renamed the other editions to just Minecraft.

As [linked](https://www.minecraft.net/en-us/article/all-news-e3) earlier (emphasis added):

>So going forward, **the edition you'll find on Xbox One, Nintendo Switch, mobile and VR will simply be known as 'Minecraft', a separate entity from 'Minecraft: Java Edition',** which is the original PC game (that we'll continue to support, of course). This means **when you buy 'Minecraft', you're buying a game that can you can play with friends across devices.**

The fact that their old .deb file hasn't been updated with the new branding is likely a mistake, as their announcement is abundantly clear about the rename.

How many people play on online servers or the "more limited" nature of the new Minecraft is irrelevant as the company producing the product has renamed it. Flathub really must respect their branding here.

**Comment by AsciiWolf** [comment]
The official Arch Linux AUR package (that is not outdated and was updated few days ago, just like the deb file) is also called [minecraft-launcher](https://aur.archlinux.org/packages/minecraft-launcher) with "Official Minecraft Launcher" in its description and "Minecraft Launcher" as desktop file name. Sorry, I don't think I will be changing the Flatpak name since it has the same name Mojang currently use in their installers/metadata/etc. Changing it would just make it more confusing for users. However, what I will change is the description when I will rename "Minecraft" to "Minecraft: Java Edition".

By the way, Mojang is aware of this Flatpak, they don't officially support it, but when I was discussing it with one of their employees, they did not mention any issues with the name.

**Comment by AsciiWolf** [comment]
I have tried to change the name in description as noted [here](https://github.com/flathub/com.mojang.Minecraft/pull/47#issuecomment-607174870), unfortunately it turned out to be too difficult. It would require changing the name in Arabic and Bengali which I don't know (and using online translator for this is a really bad idea). Maybe we could ask someone from [Endless](https://endlessos.com) to help us assist with this, but until this is resolved, I won't be changing anything. Sorry.

**Comment by bilelmoussaoui** [comment]
I think we should stick to whatever they have on their desktop file. The suggestion should go upstream and we can update the name here later

**Comment by AsciiWolf** [comment]
I have changed the first screenshot in the Flatpak AppData to a launcher screenshot that clearly shows that this is a Java Edition.

**Comment by cassidyjames** [comment]
…which doesn't help non-English speakers, screen readers, etc. :stuck_out_tongue: 

The game has been renamed, with a **new, entirely different** game getting the "Minecraft" name. Flathub is shipping it under the **wrong** name. I don't see how that's so hard to understand and fix.

**Comment by AsciiWolf** [comment]
Actually, Mojang is shipping the game under the wrong name in their **official** installation package. Also, you talk about non-English speakers, yet the PR you sent was not useful at all for non-English speakers, because you changed only the English name/description. If you can prepare a **proper** PR with name and description changed in all languages, including Arabic and Bengali (which I am not able to do, if I don't count using a translator, which is unacceptable to me), feel free to, but until then it is pointless to discuss this matter any further. And even after you'd submit the proper PR, we would need to ask people from Endless, if they are fine with this change, since Minecraft is an important Flatpak for them and was originally maintained by them.

**Comment by AsciiWolf** [comment]
Also, I am with @bilelmoussaoui on this: Discussing a name change should first be talked with people from Mojang that prepare the official installers.

**Comment by cassidyjames** [comment]
@AsciiWolf I did reach out to Mojang, but they have so far been unresponsive (it seems that they don't know/care that Flathub exists, and that Linux/Java Edition support is lower priority). But considering all of their documentation clearly spells out the name change, it just seems like an oversight that their Linux builds haven't been updated. 

I'll continue to reach out to them and ask for an official stance on Flathub's misnaming of their product, though.

**Comment by AsciiWolf** [comment]
Can you please stop ignoring what I talked about multiple times? I **was not** talking about this Flatpak name, but about their _official installer_ name/description.

**Comment by AsciiWolf** [comment]
@nedrichards Do you know someone from Endless who could be added to this discussion?

**Comment by cassidyjames** [comment]
@AsciiWolf I'm not ignoring that. I addressed it directly:

>But considering all of their documentation clearly spells out the name change, it just seems like an oversight that their Linux builds haven't been updated.

And as stated, I've reached out and will continue to do so. But I don't agree that their Debian installer that carries the old branding should overrule the very clear copy detailing the change on their website.

**Comment by AnalogCyan** [comment]
Response from one of the Minecraft devs [on twitter](https://twitter.com/Dinnerbone/status/1251036188359774211), they think the launcher should remain called simply _Minecraft_, as Java Edition won't always be the only game in the launcher. Additionally, the Windows installer and launcher appears to use the same sort of terminology that the Linux ones do, being simply _MinecraftInstaller.msi_ and _Minecraft Launcher_, so if the Linux launcher is wrong, so is the Windows one.
