### ISSUE TITLE
What's the difference between the flatpak version and the original version from minecraft website? Also Does the flatpak version support i386 (32bit) architecture?

### ISSUE THREAD

**Issue by This-Is-a-Username-lol** [flathub/com.mojang.Minecraft#68]

**Comment by AsciiWolf** [comment]
This Flatpak is based on the official version from minecraft.net. It is x86_64 only since the official launcher is x86_64 only, so no i386 or arm/aarch64, unfortunately. The main difference is that this Flatpak is sandboxed and also that it should work out-of-box on all distributions that support Flatpak. It is, however, unsupported by Mojang. But it should work fine.
