### ISSUE TITLE
Using old versions of Minecraft

### ISSUE THREAD

**Issue by cerulis64** [flathub/com.mojang.Minecraft#70]
Older versions of Minecraft like 1.8.9 can not connect to servers most likely because the Flatpak package uses OpenJDK 11

error when connecting to servers on 1.8.9:
> Internal Exception: java.lang.RuntimeException: Unable to access address of buffer

1.8.9 is still popular among people in the PVP community because it is the last version before the combat update (1.9) that many people do not enjoy playing on.
Additionally, 1.8.9 uses less system resources because it has less features than the latest versions, possibly allowing a smoother game play experience.

**Solution:** replace OpenJDK 11 with OpenJDK 8.

**Comment by AsciiWolf** [comment]
You should be able to use openjdk8 by manually installing the `org.freedesktop.Sdk.Extension.openjdk8` extension. It will be available in `/app/jdk8`.

**Comment by cerulis64** [comment]
Even so, it will not work out of the box, and it may be confusing for non-technical users.
As far as i know, switching from OpenJDK 11 to 8 causes any issues.

**Comment by AsciiWolf** [comment]
I agree that the current solution may be confusing for non-technical users, however I don't think that using old openjdk8 for all Minecraft versions is the best solution. Originally, this Flatpak was using openjdk9 and there were many issues with it including framerate issues. Most of the issues got fixed by switching to openjdk11.

**Comment by AsciiWolf** [comment]
I agree that the current solution may be confusing for non-technical users, however I don't think that using old openjdk8 for all Minecraft versions is the best solution. Originally, this Flatpak was using openjdk9 and there were many issues with it including framerate issues. Most of the issues got fixed by switching to openjdk11.
