### ISSUE TITLE
Minecraft does not create its folder within ~/.var/app.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [flathub/com.mojang.Minecraft#82]

**Comment by AsciiWolf** [comment]
Hmm. This could be fixed by #83. Please, try the test build from there and let us know. Thanks!

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
http://github.com/flathub/com.mojang.Minecraft/issues/82#issuecomment-869172072
Do I just install the build from `https://dl.flathub.org/build-repo/49988/com.mojang.Minecraft.flatpakref` to test it?

**Comment by AsciiWolf** [comment]
Well, it looks like that the build from #83 is broken, unfortunately. See my comment: https://github.com/flathub/com.mojang.Minecraft/pull/83#issuecomment-869175228

So, there's no point in testing the new build. Sorry for the noise.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
http://github.com/flathub/com.mojang.Minecraft/issues/82#issuecomment-869540185
That is alright. I actually cannot verify that this issue has occurred, as my installation is now system-wide, and my file manager at the time of this report was sandboxed due to incorrect flatpack permissions, so today is a bad day for both of us.

I shall close this until I can verify its existence.
