### ISSUE TITLE
Bugs/glitches maybe some improvements with it

### ISSUE THREAD

**Issue by UnknownBinary009** [flathub/com.mojang.Minecraft#91]
Hello could you guys please fix some bugs/glitches about the Launcher

1. Launcher location should be in .minecraft and not com.mojang.Minecraft/.minecraft
2. Launcher skins gets not rendered overall just the legs gets rendered
3. Old versions needs to work
4. Accounts should get saved like. Microsoft/Mojang people needs to relogin all the time when launcher gets a restart
5. All versions under 1.17 needs java 8
6. Modded version like ( Forge, Fabric, Optifine ) should get fixed

Ok i am done with my issues/glitches/bugs i hope you guys fix it.. take the time you need and
have a good day! :D

**Comment by AsciiWolf** [comment]
Thanks for your report!

ad 1. Yeah, the correct location is _~/.minecraft_, but since this Flatpak is sandboxed, it is stored inside the Flatpak application directory, therefore _~/.var/app/com.mojang.Minecraft/.minecraft_. Using a standard, non-sandboxed directory is not a good idea and would bring new problems (especially now when we need to handle the migration from xdg to non-xdg dir), at least in my opinion.
ad 2. Hmm, this is strange. Do you have any screenshots of this behavior? I am using the standard Launcher skin and it works fine on my system.
ad 3. They should work fine now - recent launcher now uses a bundled Java.
ad 4. Yeah, I have experienced this in the past too, but this seems to be a Mojang bug that is not Flatpak-related.
ad 5. Recent launcher now uses a bundled Java, including Java 8, so old MC versions should work fine now.
ad 6. They should work much better now. Feel free to retest and report any issues. :-)

**Comment by SystemlessDev** [comment]
> Launcher location should be in .minecraft and not com.mojang.Minecraft/.minecraft

Not possible due to sandboxing, as AsciiWolf said above

> Launcher skins gets not rendered overall just the legs gets rendered

Known issue with the launcher itself. Nothing we can do to fix it.

> Old versions needs to work

Works

> Accounts should get saved like. Microsoft/Mojang people needs to relogin all the time when launcher gets a restart

If your accounts aren't saved then it's either an issue on your side or the launcher side. It works perfectly well for me.

> All versions under 1.17 needs java 8

That's handled by the launcher itself.

> Modded version like ( Forge, Fabric, Optifine ) should get fixed

Those has always worked. You just need to change the installation path to something like `~/.var/app/com.mojang.Minecraft/.minecraft`

@AsciiWolf close this issue
